# details: https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  apt_packages:
    - make

formats: all

python:
  install:
    # - requirements: docs/requirements.txt
    # - requirements: requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
  system_packages: false

# you can choose either sphinx or mkdocs as document build tool.

sphinx:
  builder: html
  configuration: docs/api/conf.py
  fail_on_warning: false

# mkdocs:
#   configuration: mkdocs.yml
#   fail_on_warning: false

submodules:
  include: []
  exclude: all
  recursive: false

search:
  ranking:
    tests/*: -10
    tutorial.html: 10
  ignore:
    - 404.html
