version: '3.9'


services:
  py:
    build:
      context: ..
      dockerfile: 
        docker/Dockerfile
    command: [
      /usr/bin/python3,
      ./src/__main__.py,
    ]
    # devices:
    #   - /dev/video0:/dev/video0
    env_file:
      - common.env
    image: kagemeka/sushida-py
    network_mode: host
    restart: unless-stopped
    # runtime: nvidia
    tty: true
    volumes:
      - type: bind
        bind:
          propagation: rprivate
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        read_only: false
        volume:
          nocopy: true
      - type: bind
        source: $ROOT
        target: /root/$PROJECT
    working_dir: /root/$PROJECT